services:
  service:
    build:
      context: ./${SERVICE_NAME}
      dockerfile: Dockerfile
    image: ${SERVICE_NAME}:dev
    container_name: ${SERVICE_NAME}
    working_dir: /usr/src/app
    command: ["sh", "-c", "sleep infinity"]
    develop:
      watch:
        - path: ./${SERVICE_NAME}/Dockerfile
          action: rebuild
        - path: ./${SERVICE_NAME}/package.json
          action: rebuild
        - path: ./${SERVICE_NAME}
          target: /usr/src/app
          action: sync
          ignore:
            - "**/node_modules/**"
            - ".git/**"